# PyInstaller spec for ProductScraper Windows EXE.
#
# Build command (run on Windows):
#   pip install pyinstaller
#   pyinstaller build.spec
#
# Output: dist/ProductScraper.exe  (single-file, no console window)

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None

# Collect all data files bundled by flask/webview
datas = [
    # Ship the entire frontend directory inside the bundle
    ("frontend", "frontend"),
]
datas += collect_data_files("webview")

hidden_imports = [
    # Crawler modules (auto-imported at runtime via importlib)
    "crawlers.basalam",
    "crawlers.emalls",
    "crawlers.snappshop",
    "crawlers.shopino",
    # Supporting modules
    "exporters.sazito_csv",
    "memory",
    "models",
    # Flask internals that PyInstaller misses
    "flask",
    "flask.json.provider",
    "jinja2",
    "jinja2.ext",
    "werkzeug",
    "werkzeug.serving",
    "werkzeug.debug",
    # PyWebView Windows backend (Edge/WebView2)
    "webview",
    "webview.platforms.winforms",
    "clr",
    "System",
    "System.Windows.Forms",
]
hidden_imports += collect_submodules("flask")

a = Analysis(
    ["gui.py"],
    pathex=["."],
    binaries=[],
    datas=datas,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "numpy", "pandas"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="EComCrawler",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    icon='assets/icon.ico',  # generated by create_icon.py before PyInstaller runs
    console=False,       # no black terminal window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
